config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  root 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'
  get 'search' => 'searches#search'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "glyphicon glyphicon-heart", remote: true %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "glyphicon glyphicon-heart-empty", remote: true %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn',  book: @book ) %>");

app/views/favorites/destroy.js.erb
$("#favorite-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn',  book: @book ) %>");