config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get 'follows' => 'relationships#follower'
    get 'followers' => 'relationships#followed'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  root 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'
  get 'search' => 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
    
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user!= current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books/searches_helper.rb
module Books::SearchesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
		<%= form_with(model: @book, local: true) do |f| %>
        <% if @book.errors.any? %>
        <div class="notifications">
          <div class="notice"><%= @book.errors.count %>errors prohibited this obj from being saved:</div>
        </div>
        <div class="alert alert-warning">
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
		<%= render "books/form", book: @book %>
		<% end %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		|
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="search-form">
        <%= form_with(model:@search, url: search_path, method: :get, local: true) do |f| %>
          <%= f.text_field 'search[content]' %>
          <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
          <%= f.submit '検索', class: "btn btn-default" %>
        <% end %>
</div>
<%= form_with(model: @book, local: true) do |f| %>
          <% if @book.errors.any? %>
            <div class="notifications">
              <div class="notice"><%= @book.errors.count %>errors prohibited this obj from being saved:</div>
            </div>
            <div class="alert alert-warning">
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		
		
 　    <% if current_user.following?(current_user) %>
        <%= link_to 'フォロー外す', user_relationships_path(current_user.id), method: :delete, class: "btn btn-default" %>
      <% else %>
   　    <%= link_to 'フォローする', user_relationships_path(current_user.id), method: :POST , class: "btn btn-primary"%>
      <% end %>
   

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				    <td class="favorite-btn">
				       <div id="favorite-<%= book.id %>">
				    	<%= render 'favorites/favorite-btn', book: book %>
				       </div>
				    </td>
					<td>
						<ul class="inline-meta">
              <%= link_to "コメント数: #{book.book_comments.count} ", book_path(book) %>
            </ul>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book_new%>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
					<td>
            <h4 class="comment-count">コメント数：<%= @book.book_comments.count %></h4>
					</td>
		</table>
						  <table class="comments_<%= @book.id %>">
                <%= render 'book_comments/comments', book: @book %> 
            </table>
						<%= form_with(model:[@book, @book_comment],url: book_book_comments_path(@book.id), method: :post ) do |f| %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                </div>
              </div>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
	</div>
</div>